"""Init

Revision ID: e7e47b71a7c8
Revises: 20dee0bcc5e1
Create Date: 2022-12-20 12:26:54.645390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7e47b71a7c8'
down_revision = '20dee0bcc5e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
