"""Init

Revision ID: ac9e5b2d991a
Revises: d6c7ead947f1
Create Date: 2022-12-20 11:47:22.882685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac9e5b2d991a'
down_revision = 'd6c7ead947f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
