"""Init

Revision ID: d6c7ead947f1
Revises: 233aa49bc990
Create Date: 2022-12-20 11:44:42.383047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6c7ead947f1'
down_revision = '233aa49bc990'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
