"""Init

Revision ID: 20dee0bcc5e1
Revises: ac9e5b2d991a
Create Date: 2022-12-20 12:05:38.084038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20dee0bcc5e1'
down_revision = 'ac9e5b2d991a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
