"""Init

Revision ID: 612c59005ce4
Revises: e7e47b71a7c8
Create Date: 2022-12-20 13:55:50.803424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '612c59005ce4'
down_revision = 'e7e47b71a7c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Client_id'), 'Client', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Client_id'), table_name='Client')
    op.drop_table('Client')
    # ### end Alembic commands ###
